### ISSUE TITLE
DO FIRST! Add user authentication with Bcrypt

### ISSUE THREAD

**Issue by Dreedle** [Dreedle/QuoteBoard#5]
It would make sense for this issue to be taken care of FIRST.
Add user authentication as opposed to the current state, where you pseudo-sign by selecting which person you are.
This will solve a lot of current unpleasantries in navigating the site, such as the fact that when you pseudo sign-in as a person and then click on the body of a quote, you are pseudo logged-out. 
The nav bar will have to be changed from the dropdown menu that is being used now which asks "Who are you?", and login/logout buttons will need to be added to navbar.

**Comment by Kedevlin** [comment]
I'll work on this issue! Is the idea to have everything except reading capabilities restricted to logged-in users?  In other words, guests will be able to view all the quotes, comments, and people.  When a new user registers, this will create a new person object (from the People model), right? And only the logged in person associated with a given quote or comment will be able to edit or delete that quote or comment.

**Comment by Dreedle** [comment]
Kelly, yay! Yes, please. What you described is just right. I made you a collaborator. Thanks!

**Comment by Dreedle** [comment]
This issue was finished and merged without a pull request (only because Kelly didn't manage to open on before I impatiently merged the changes myself).
